### ISSUE TITLE
Invalid UI state while creating issue for repo with no push access

### ISSUE THREAD

**Issue by mustafa01ali** [github/android#680]
Navigate to any repo to which you do not have push access and click on create issue.

![device-2015-01-14-154202](https://cloud.githubusercontent.com/assets/767705/5748223/ecd4a400-9c03-11e4-9c27-d7f153a02bf8.png)

```java
01-14 15:39:43.623  20158-20158/com.github.mobile E/roboguice﹕ Throwable caught during background processing
    org.eclipse.egit.github.core.client.RequestException: Must have push access to view repository collaborators. (403)
            at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:552)
            at org.eclipse.egit.github.core.client.GitHubClient.get(GitHubClient.java:740)
            at org.eclipse.egit.github.core.service.GitHubService.check(GitHubService.java:167)
            at org.eclipse.egit.github.core.service.CollaboratorService.isCollaborator(CollaboratorService.java:102)
            at com.github.mobile.ui.issue.EditIssueActivity$7.run(EditIssueActivity.java:389)
            at com.github.mobile.ui.issue.EditIssueActivity$7.run(EditIssueActivity.java:385)
            at com.github.mobile.accounts.AuthenticatedUserTask.call(AuthenticatedUserTask.java:79)
            at roboguice.util.SafeAsyncTask$Task.doCall(SafeAsyncTask.java:204)
            at roboguice.util.SafeAsyncTask$Task.call(SafeAsyncTask.java:170)
            at roboguice.util.SafeAsyncTask$Task.call(SafeAsyncTask.java:158)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
            at dalvik.system.VMStack.getThreadStackTrace(Native Method)
            at java.lang.Thread.getStackTrace(Thread.java:580)
            at roboguice.util.SafeAsyncTask.execute(SafeAsyncTask.java:90)
            at com.github.mobile.ui.issue.EditIssueActivity.checkCollaboratorStatus(EditIssueActivity.java:385)
            at com.github.mobile.ui.issue.EditIssueActivity.onCreate(EditIssueActivity.java:158)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

```

**Comment by Meisolsson** [comment]
This is actually just another one of my layout fails that i forgot when switching to Toolbars. Will submit a PR tomorrow.

If you find more places where something is covering the Action Bar. Make it an issue or add it here
